// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlrjjjumijmpujtbrtil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpscmpqanVtaWptcHVqdGJydGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzEzMDUsImV4cCI6MjA2Nzc0NzMwNX0.Le5NW68Q9FvuMKfRJ3ShpjcfjbUpazWl7_tZgvo7U6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});